package org.gofleet.openLS.ddbb.bean;

// Generated 07-oct-2011 14:06:19 by Hibernate Tools 3.4.0.CR1

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AdvancedPoiTemplate generated by hbm2java
 */
@Entity
@Table(name = "advanced_poi", schema = "public")
public class AdvancedPoi implements java.io.Serializable {

	private int id;
	private String key;
	private String value;
	private Poi poi;

	public AdvancedPoi() {
	}

	public AdvancedPoi(int id, String key, String value, Poi poi) {
		this.id = id;
		this.key = key;
		this.value = value;
		this.poi = poi;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "key", nullable = false)
	public String getKey() {
		return this.key;
	}

	public void setKey(String key) {
		this.key = key;
	}

	@Column(name = "value", nullable = false)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	@ManyToOne(cascade = CascadeType.ALL)
	public Poi getPoi() {
		return this.poi;
	}

	public void setPoi(Poi poi) {
		this.poi = poi;
	}

}
