package org.gofleet.openLS.ddbb.bean;

// Generated 07-oct-2011 14:06:19 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Configuration generated by hbm2java
 */
@Entity
@Table(name = "configuration", schema = "public")
public class Configuration implements java.io.Serializable {

	private String id;
	private String valor;
	private boolean updatable;

	public Configuration() {
	}

	public Configuration(String id, boolean updatable) {
		this.id = id;
		this.updatable = updatable;
	}

	public Configuration(String id, String valor, boolean updatable) {
		this.id = id;
		this.valor = valor;
		this.updatable = updatable;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, length = 20)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "valor")
	public String getValor() {
		return this.valor;
	}

	public void setValor(String valor) {
		this.valor = valor;
	}

	@Column(name = "updatable", nullable = false)
	public boolean isUpdatable() {
		return this.updatable;
	}

	public void setUpdatable(boolean updatable) {
		this.updatable = updatable;
	}

}
