package org.gofleet.openLS.ddbb.types;

// Generated 07-oct-2011 14:06:19 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Entity;

/**
 * StreetTemplate generated by hbm2java
 */
@Entity
public class GeocodingAddressType implements java.io.Serializable {

	private String street;
	private String munsub;
	private String mun;
	private String subcountry;
	private String country;

}
