package org.gofleet.openLS.ddbb.bean;

// Generated 07-oct-2011 14:06:19 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import com.vividsolutions.jts.geom.Geometry;

/**
 * PoiTemplate generated by hbm2java
 */
@Entity
@Table(name = "poi", schema = "public")
public class Poi implements java.io.Serializable {

	private int id;
	private String name;
	private Geometry geometry;

	public Poi() {
	}

	public Poi(int id) {
		this.id = id;
	}

	public Poi(int id, String name, Geometry geometry) {
		this.id = id;
		this.name = name;
		this.geometry = geometry;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "geometry")
	public Geometry getGeometry() {
		return this.geometry;
	}

	public void setGeometry(Geometry geometry) {
		this.geometry = geometry;
	}

}
